name: Build & Test & Publish

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Setup npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Upload test coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npx codecov

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Setup npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Configure git
        run: |
          git config user.name ${{ secrets.GIT_BOT_USERNAME }}
          git config user.email ${{ secrets.GIT_BOT_EMAIL }}
          git remote set-url origin https://${{ secrets.BOT_TOKEN }}@github.com/dialogs/grpc-web-gateway.git
      - name: Install dependencies
        run: npm ci
      - name: Release
        run: npx lerna publish patch --yes
