name: Build & Test & Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.13.x'
      - name: Setup npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: npx lerna bootstrap
      - name: Instal flow types
        run: npx lerna exec -- "(npx flow-typed install || exit 0)"
      - name: Flow check
        run: npx flow check
      - name: Release
        run: npx lerna publish patch --yes
